# Generated by Django 5.1.7 on 2026-05-23 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size_unit', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(blank=True, max_length=100)),
                ('probable_cause', models.TextField(blank=True)),
                ('influence_on_condition', models.TextField(blank=True)),
                ('preliminary_condition_category', models.CharField(blank=True, max_length=100)),
                ('final_condition_category', models.CharField(blank=True, max_length=100)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
