# Generated by Django 5.1.7 on 2026-05-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0002_initial'),
        ('elements', '0002_initial'),
        ('inspections', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_defects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspectionproject'),
        ),
        migrations.AddField(
            model_name='defect',
            name='structural_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='elements.structuralelement'),
        ),
    ]
