# Generated by Django 5.1.7 on 2026-05-23 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('inspection_reason', models.TextField()),
                ('inspection_goal', models.TextField()),
                ('inspection_type', models.CharField(choices=[('planned', 'Planned'), ('exceptional', 'Exceptional'), ('monitoring', 'Monitoring')], default='planned', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Draft', max_length=32)),
                ('final_condition_category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TechnicalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_basis', models.TextField(blank=True)),
                ('survey_goal', models.TextField(blank=True)),
                ('building_parts', models.TextField(blank=True)),
                ('engineering_systems', models.TextField(blank=True)),
                ('required_methods', models.TextField(blank=True)),
                ('result_requirements', models.TextField(blank=True)),
                ('deadlines', models.TextField(blank=True)),
                ('output_documentation', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structures', models.TextField(blank=True)),
                ('zones', models.TextField(blank=True)),
                ('methods', models.TextField(blank=True)),
                ('tools_and_devices', models.TextField(blank=True)),
                ('measurements', models.TextField(blank=True)),
                ('photo_requirements', models.TextField(blank=True)),
                ('responsible_executors', models.TextField(blank=True)),
                ('completeness_checklist', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
