# Generated by Django 5.1.7 on 2026-05-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionproject',
            name='building_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='objects.buildingobject'),
        ),
    ]
