# Generated by Django 5.1.7 on 2026-05-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionproject',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionproject',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='inspection_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaltask',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_task', to='inspections.inspectionproject'),
        ),
        migrations.AddField(
            model_name='workprogram',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_program', to='inspections.inspectionproject'),
        ),
    ]
