# Generated by Django 5.1.7 on 2026-05-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_controlled_dictionaries'),
        ('reports', '0005_reporttemplate_reporttemplateblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionproject',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='reports.reporttemplate'),
        ),
    ]
