# Generated by Django 5.1.7 on 2026-05-23 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_for_report', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('object', 'Object'), ('project', 'Project'), ('element', 'Element'), ('defect', 'Defect'), ('measurement', 'Measurement'), ('report', 'Report')], max_length=32)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
