# Generated by Django 5.1.7 on 2026-05-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0002_initial'),
        ('files', '0001_initial'),
        ('inspections', '0001_initial'),
        ('measurements', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionfile',
            name='building_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='objects.buildingobject'),
        ),
        migrations.AddField(
            model_name='inspectionfile',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='defects.defect'),
        ),
        migrations.AddField(
            model_name='inspectionfile',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='measurements.measurement'),
        ),
        migrations.AddField(
            model_name='inspectionfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inspections.inspectionproject'),
        ),
    ]
