# Generated by Django 5.1.7 on 2026-05-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0002_initial'),
        ('files', '0002_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionfile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.report'),
        ),
        migrations.AddField(
            model_name='inspectionfile',
            name='structural_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='elements.structuralelement'),
        ),
    ]
