# Generated by Django 5.1.7 on 2026-05-23 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('cadastral_number', models.CharField(blank=True, max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('reconstruction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('floors_count', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('structural_scheme', models.CharField(blank=True, max_length=255)),
                ('foundation_material', models.CharField(blank=True, max_length=255)),
                ('wall_material', models.CharField(blank=True, max_length=255)),
                ('floor_material', models.CharField(blank=True, max_length=255)),
                ('roof_material', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
