# Generated by Django 5.1.7 on 2026-05-23 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_type', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('measured_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='defects.defect')),
            ],
            options={
                'ordering': ('-measured_at',),
            },
        ),
    ]
