# Generated by Django 5.1.7 on 2026-05-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_dictionaryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionCategory',
        ),
        migrations.DeleteModel(
            name='DefectType',
        ),
        migrations.DeleteModel(
            name='ElementType',
        ),
        migrations.DeleteModel(
            name='InspectionMethod',
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
