# Generated by Django 5.1.7 on 2026-05-23 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('axes', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_accessible', models.BooleanField(default=True)),
                ('inspection_method', models.CharField(blank=True, max_length=255)),
                ('visual_condition', models.CharField(blank=True, max_length=255)),
                ('has_defects', models.BooleanField(default=False)),
                ('no_defects_comment', models.CharField(blank=True, max_length=255)),
                ('condition_category', models.CharField(blank=True, max_length=100)),
                ('conclusion', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('not_required', 'Не требуются'), ('observe', 'Требуется наблюдение'), ('repair', 'Требуется ремонт'), ('detailed_survey', 'Требуется детальное обследование')], default='not_required', max_length=32)),
            ],
            options={
                'ordering': ('element_type', 'name'),
            },
        ),
    ]
