# Generated by Django 5.1.7 on 2026-05-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_snapshot_pipeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-generated_at', '-created_at')},
        ),
    ]
