# Generated by Django 5.1.7 on 2026-05-30 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReportTemplateBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('title_page', 'Титульный лист'), ('table_of_contents', 'Содержание'), ('introduction', 'Введение'), ('inspection_information', 'Сведения об обследовании'), ('object_information', 'Информация об объекте'), ('technical_documentation_analysis', 'Анализ технической документации'), ('brief_characteristics', 'Краткая характеристика объекта'), ('visual_measurement_control', 'Результаты визуального и измерительного контроля'), ('detailed_instrumental_control', 'Результаты детального инструментального контроля'), ('environmental_impact', 'Определение степени влияния внешних воздействий'), ('verification_calculations', 'Результаты поверочных расчетов'), ('result_analysis', 'Анализ результатов технического обследования'), ('conclusions', 'Выводы'), ('recommendations', 'Рекомендации'), ('appendices', 'Приложения')], max_length=64)),
                ('title_override', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('template', 'block_type'), name='unique_template_block_type')],
            },
        ),
    ]
